server:
  port: 8080

spring:
  application:
    name: cadastreeei
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/${DATABASE_DB:cadastreeei}
    username: ${DATABASE_USER:username}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect