version: '3.8'

networks:
  cadastreeei-network:
    driver: bridge

services:
  cadastreeei-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cadastreeei
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - cadastreeei-network

  cadastreeei-app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - cadastreeei-db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=cadastreeei-db
      - DATABASE_DB=cadastreeei
      - DATABASE_USER=username
      - DATABASE_PASSWORD=password
    networks:
      - cadastreeei-network